<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
    <head>
        <title><?php echo $this->fetch('title'); ?></title>
    </head>
    <body>
        <?php echo $this->fetch('content'); ?>

        <p>This email has been automatically generated by <a href="https://www.indesore.com">Indesore ERP</a></p>
    </body>
</html>