<?php

App::uses('AppController', 'Controller');

/**
 * Departments Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Department $Department
 * @property PaginatorComponent $Paginator
 */
class DepartmentsController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->Department->recursive = 0;
        $conditions = array();
        if (!empty($this->request->data['Src']['nm'])) {
            $conditions[] = array("Department.name LIKE '%" . $this->request->data['Src']['nm'] . "%'");
        }
        if (!empty($this->request->data['Src']['company_id'])) {
            $conditions[] = array("Department.company_id" => $this->request->data['Src']['company_id']);
        }
        $this->Paginator->settings = array('conditions' => $conditions, 'order' => array('Department.id' => 'DESC'));
        $this->set('departments', $this->Paginator->paginate());

        $this->loadModel('User');
        $users = $this->User->find('list');
        $companies = $this->Department->Company->find('list', array('conditions' => array('status' => E_ERROR), 'order' => array('name' => 'ASC')));
        $this->set(compact('users', 'companies'));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Department->create();
            //pr($this->request->data,1);
            $this->request->data['Department']['entry_by'] = $this->Auth->user('id');
            if ($this->Department->save($this->request->data)) {

                $data = $this->encode($this->request->data);
                $this->curlSend('departments/ajax_add', array('_t_' => time(), 'd' => $data));

                $this->Flash->success('The department has been saved.');
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error('The department could not be saved. Please, try again.');
            }
        }
        $companies = $this->Department->Company->find('list', array('conditions' => array('status' => E_ERROR), 'order' => array('name' => 'ASC')));
        $this->set(compact('companies'));
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Department->exists($id)) {
            throw new NotFoundException(__('Invalid department'));
        }
        if ($this->request->isPost() || $this->request->isPut()) {
            $this->request->data['Department']['edit_by'] = $this->Auth->user('id');
            if ($this->Department->save($this->request->data)) {

                $data = $this->encode($this->request->data);
                $this->curlSend('departments/ajax_edit', array('_t_' => time(), 'd' => $data));

                $this->Flash->success('The department has been updated.');
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Flash->error('The department could not be updated. Please, try again.');
            }
        } else {
            $options = array('conditions' => array('Department.' . $this->Department->primaryKey => $id));
            $this->request->data = $this->Department->find('first', $options);
        }
        $companies = $this->Department->Company->find('list', array('conditions' => array('status' => E_ERROR), 'order' => array('name' => 'ASC')));
        $this->set(compact('companies'));
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Department->id = $id;
        if (!$this->Department->exists()) {
            throw new NotFoundException(__('Invalid department'));
        }

        $this->loadModel('Designation');
        $designation = $this->Designation->find('first', array('conditions' => array('department_id' => $id)));
        if (count($designation) > 0) {
            $this->Flash->error('The department has designation, could not be deleted.');
        } else {
            $this->request->allowMethod('post', 'delete');
            if ($this->Department->delete()) {

                $data = $this->encode($id . '|' . time());
                $this->curlSend('departments/ajax_delete', array('_t_' => time(), 'd' => $data));

                $this->Flash->success('The department has been deleted.');
            } else {
                $this->Flash->error('The department could not be deleted. Please, try again.');
            }
            return $this->redirect(array('action' => 'index'));
        }
    }

    /**
     * check username exist by ajax
     *
     * @throws NotFoundException
     * @param string $username
     * @return void
     */
    public function ajax_getdepartments() {
        $this->layout = 'ajax';

        $departments = $this->Department->find('list', array('conditions' => array('company_id' => $this->request->data('company_id')), 'order' => array('name' => 'ASC')));
        $this->set('departments', $departments);
        $this->set('model', $this->request->data('model'));
        $this->set('label', $this->request->data('label'));
        $this->set('department_id', $this->request->data('department_id'));
        $this->set('not_change', $this->request->data('not_change'));
        $this->set('fld', $this->request->data('fld'));
        $this->set('required', $this->request->data('required'));
    }

    /**
     * check username exist by ajax
     *
     * @throws NotFoundException
     * @param string $username
     * @return void
     */
    public function ajax_checkdepartment() {
        $this->autoRender = FALSE;

        $conditions = ["name" => $this->request->data('ttl'), "company_id" => $this->request->data('company_id')];
        if ($this->request->data('uid')) {
            $conditions[] = ["id <> " . $this->request->data('uid')];
        }

        $user = $this->Department->find('first', array('conditions' => $conditions, 'fields' => array('id'), 'recursive' => -1));
        if (count($user) > 0) {
            echo 'Please use another name';
        } else {
            echo false;
        }
    }

}
